language: go

service:
  - docker

go:
  - 1.x
  
 
script:
 - go test -v ./...
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  
 - docker images
 - docker build -t travisheroku .
 - docker run travisheroku
 - docker tag travisheroku:latest suryanaicker/travisheroku:doc
 - docker push suryanaicker/travisheroku:doc
  
